"""empty message

Revision ID: 4ed47eb57049
Revises: 5d3f78007980
Create Date: 2025-06-07 13:36:32.739257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ed47eb57049'
down_revision: Union[str, None] = '5d3f78007980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicants', sa.Column('resume_filename', sa.Text(), nullable=False))
    op.add_column('applicants', sa.Column('extracted_resume_text', sa.Text(), nullable=True))
    op.drop_column('applicants', 'weaknesses_summary')
    op.drop_column('applicants', 'strengths_summary')
    op.drop_column('applicants', 'strengths_detailed')
    op.drop_column('applicants', 'resume_s3_object_key')
    op.drop_column('applicants', 'updated_at')
    op.drop_column('applicants', 'weaknesses_detailed')
    op.drop_column('applicants', 'overall_score')
    op.drop_column('applicants', 'created_at')
    op.drop_constraint(op.f('jobs_user_id_fkey'), 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'company_name')
    op.drop_column('jobs', 'creation_date')
    op.drop_column('jobs', 'job_location')
    op.drop_column('jobs', 'job_department')
    op.drop_column('jobs', 'updated_at')
    op.drop_column('jobs', 'job_title')
    op.drop_column('jobs', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('job_title', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('job_department', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('job_location', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('creation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('company_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('jobs_user_id_fkey'), 'jobs', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.add_column('applicants', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('applicants', sa.Column('overall_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('applicants', sa.Column('weaknesses_detailed', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('applicants', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('applicants', sa.Column('resume_s3_object_key', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('applicants', sa.Column('strengths_detailed', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('applicants', sa.Column('strengths_summary', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('applicants', sa.Column('weaknesses_summary', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('applicants', 'extracted_resume_text')
    op.drop_column('applicants', 'resume_filename')
    # ### end Alembic commands ###
