"""Initial migration with users, jobs, and applicants tables

Revision ID: 5d3f78007980
Revises: 
Create Date: 2025-06-07 12:16:38.989007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d3f78007980'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clerk_id', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('clerk_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('jobs',
    sa.Column('job_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_url', sa.Text(), nullable=False),
    sa.Column('company_name', sa.Text(), nullable=True),
    sa.Column('job_title', sa.Text(), nullable=True),
    sa.Column('job_location', sa.Text(), nullable=True),
    sa.Column('job_department', sa.Text(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('processing_status', sa.Enum('not_started', 'processing', 'completed', 'failed', name='jobprocessingstatus'), nullable=False),
    sa.Column('extracted_job_description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('applicants',
    sa.Column('applicant_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('resume_s3_object_key', sa.Text(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('strengths_summary', sa.JSON(), nullable=True),
    sa.Column('weaknesses_summary', sa.JSON(), nullable=True),
    sa.Column('strengths_detailed', sa.JSON(), nullable=True),
    sa.Column('weaknesses_detailed', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('processing_status', sa.Enum('not_started', 'processing', 'completed', 'failed', name='resumeprocessingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('applicant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applicants')
    op.drop_table('jobs')
    op.drop_table('users')
    # ### end Alembic commands ###
